// Whether Apple's captured records are on disk, decided once for both crates
// that read them.
//
// `include!`d by `reims-vgpu-wire/build.rs` and `reims-vgpu/build.rs` rather
// than copied, because the facts here — the directory override, the two file
// names, and what `REIMS_WIRE_FIXTURES_REQUIRED` means — must not fork between
// the two suites that stand down without them. A build-dependency crate for
// twenty lines would cost more than it carries, and a build script has no
// smaller unit to share from.
//
// It sits beside the capture harness that writes the files it looks for, which
// is the one directory where "what the oracle produces and where" is already
// the subject. It is not compiled into either crate — build scripts include it.

/// Emit `wire_fixtures` and `wire_inventory` for whichever oracle outputs exist.
///
/// Presence is a **build-time** fact so the tests that need it can carry
/// `#[cfg_attr(not(wire_fixtures), ignore = "…")]` and libtest can print
/// `ignored` for each one. That is the whole point of doing it here: the
/// arrangement this replaces returned early inside each test body, so 36 tests
/// that measured nothing reported `ok` in 0.00 s across two crates — the only
/// layout-truth tests in the project, reading exactly like coverage on every
/// checkout without the fixtures.
///
/// The two outputs are probed separately so a stale capture is distinguishable
/// from a missing one: `inventory.json` is regenerated by
/// `wire-oracle.sh --inventory` and `fixtures.json` by the sweep, and having one
/// without the other is a normal intermediate state that should stand down only
/// the tests that read the absent half.
fn probe_wire_fixtures(default_dir: &str) {
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_DIR");
    println!("cargo:rerun-if-env-changed=REIMS_WIRE_FIXTURES_REQUIRED");
    println!("cargo:rustc-check-cfg=cfg(wire_fixtures)");
    println!("cargo:rustc-check-cfg=cfg(wire_inventory)");

    let dir = std::env::var("REIMS_WIRE_FIXTURES_DIR").unwrap_or_else(|_| default_dir.to_string());
    let required = std::env::var("REIMS_WIRE_FIXTURES_REQUIRED").is_ok();

    for (file, cfg) in [
        ("fixtures.json", "wire_fixtures"),
        ("inventory.json", "wire_inventory"),
    ] {
        let path = format!("{dir}/{file}");
        // Cargo re-runs on a watched path appearing as well as changing, so a
        // capture taken after the build is picked up without a manual touch.
        println!("cargo:rerun-if-changed={path}");
        if std::path::Path::new(&path).is_file() {
            println!("cargo:rustc-cfg={cfg}");
        } else if required {
            // The runtime assertion this replaces cannot fire any more — an
            // ignored test never runs to check it — so failing the build is
            // what keeps REQUIRED meaning "these must have run".
            panic!(
                "REIMS_WIRE_FIXTURES_REQUIRED is set but there is no {file} at \
                 {dir}; regenerate with scripts/wire-oracle/wire-oracle.sh"
            );
        }
    }
}
